// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvfxjmxzewsbxgqvaysm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2ZnhqbXh6ZXdzYnhncXZheXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjA2NDksImV4cCI6MjA2NTMzNjY0OX0.p3Dj-aI6yoV64ztVSVYzMvzF4srh9i_OkvxQo6Ig0TM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);